In [1]:
import numpy as np

# 1. Array Creation
arr_1d = np.array([1, 8, 27, 64])
arr_2d = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]])
arr_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[1, 2, 3, 4], [9, 10, 11, 12]]])

# 2. Displaying Array Information (Attributes)
print("--- 1D Array ---")
print("Array:\n", arr_1d)
print("Dimensions:", arr_1d.ndim)
print("Shape:", arr_1d.shape)
print("Data Type:", arr_1d.dtype)

print("\n--- 2D Array ---")
print("Array:\n", arr_2d)
print("Dimensions:", arr_2d.ndim)
print("Shape:", arr_2d.shape)
print("Data Type:", arr_2d.dtype)
print("Strides:", arr_2d.strides)

print("\n--- 3D Array ---")
print("Array:\n", arr_3d)
print("Dimensions:", arr_3d.ndim)
print("Shape:", arr_3d.shape)

# 3. Basic Array Operations
print("\n--- Array Operations ---")
# Reshaping
reshaped = arr_1d.reshape(2, 2)
print("Reshaped 1D (2x2):\n", reshaped)

# Array Arithmetic
sum_array = arr_1d + 5
print("Array + 5:\n", sum_array)

# Slicing
print("Slicing 2D Array (First 2 rows, first 2 cols):\n", arr_2d[:2, :2])

--- 1D Array ---
Array:
 [ 1  8 27 64]
Dimensions: 1
Shape: (4,)
Data Type: int64

--- 2D Array ---
Array:
 [[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]
Dimensions: 2
Shape: (3, 4)
Data Type: int64
Strides: (32, 8)

--- 3D Array ---
Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]
Dimensions: 3
Shape: (2, 2, 4)

--- Array Operations ---
Reshaped 1D (2x2):
 [[ 1  8]
 [27 64]]
Array + 5:
 [ 6 13 32 69]
Slicing 2D Array (First 2 rows, first 2 cols):
 [[1 2]
 [2 4]]
